# Generated by Django 3.2.13 on 2022-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221102_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='follower', to='accounts.User'),
        ),
    ]
