# Generated by Django 3.2.13 on 2022-11-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.IntegerField(choices=[(1, '⭐️'), (2, '⭐️⭐️'), (3, '⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (5, '⭐️⭐️⭐️⭐️⭐️')], default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sorted',
            field=models.CharField(max_length=20),
        ),
    ]
