
# Generated by Django 3.2.13 on 2022-11-04 14:10



from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221104_0934'),
        ('reviews', '0002_auto_20221104_1557'),
    ]

    operations = [
    ]
