# Generated by Django 3.2.13 on 2022-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
